routes/web.php
<?php

use App\Http\Controllers\Admin\Categories\CategoriesController;
use App\Http\Controllers\Admin\Orders\OrdersController;
use App\Http\Controllers\Admin\Settings\SettingsController;
use App\Http\Controllers\Admin\Dishes\DishesController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Restaurant\RestaurantController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Тестовые роуты
 */
Route::get('city', [IndexController::class, 'city']);
/** */

Route::get('/', [IndexController::class, 'index'])->name('index');
//
Route::get('/eve', [HomeController::class, 'eve'])->name('eve');

Route::post('messages', [RestaurantController::class,'comment'])->name('messages');

Route::get('/company/{id}', [IndexController::class, 'company'])->name('company');
Route::get('/companies', [IndexController::class, 'companies'])->name('companies');
Route::get('/shop', function () {
    return view('shop');
})->name('shop');

// Корзина
Route::get('/cart', [CartController::class, 'index'])->name('cart');

// Ресторан
Route::as('rst.')
    ->prefix('/rst')
   // ->namespace('Restaurant')
    ->group(function () {
        Route::get('{id}', [RestaurantController::class,'index'])->name('index');
    });

// Админка
Route::as('admin.')
    ->prefix('/admin')
    //->namespace('Admin')
    ->middleware('auth')
    ->group(function () {

        Route::get('/', [AdminIndexController::class, 'index'])->name('index');

        // Раздел управления категориями
        
        Route::as('categories.')
            ->prefix('/categories')
           // ->namespace('Categories')
            ->group(function () {
                Route::get('/', [CategoriesController::class, 'index'])->name('index');
                Route::post('/', [CategoriesController::class, 'store'])->name('store');
                Route::put('/{id}', [CategoriesController::class, 'update'])->name('update');
                Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
                Route::get('/create', [CategoriesController::class, 'create'])->name('create');
                Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
            }
        );

        // Раздел управления блюдами
        Route::as('dish.')
            ->prefix('/dish')
          //  ->namespace('Dish')
            ->group(function () {
                Route::get('/', [DishesController::class, 'index'])->name('index');
                Route::get('add', [DishesController::class, 'add'])->name('add');
                Route::get('edit/{id}', [DishesController::class, 'edit'])->name('edit');
                Route::post('store', [DishesController::class, 'store'])->name('store');
                Route::post('update', [DishesController::class, 'update'])->name('update');
                Route::post('delete', [DishesController::class, 'delete'])->name('delete');

                Route::post('getDishById', [DishesController::class, 'getDishById'])->name('getDishById');
            });

        // Раздел управления заказами
        Route::as('orders.')
            ->prefix('/orders')
         //   ->namespace('Orders')
            ->group(function () {
                Route::get('/', [OrdersController::class, 'index'])->name('index');
                Route::post('/store', [OrdersController::class, 'store'])->name('store');
                Route::get('/order/{orderId}', [OrdersController::class, 'order'])->name('order');
            });

        // Раздел настройки
        Route::as('settings.')
            ->prefix('/settings')
          //  ->namespace('Settings')
            ->group(function () {
                Route::get('/', [SettingsController::class, 'index'])->name('index');
            });
    });

Route::post('/addDishInSet', [IndexController::class, 'addDishInSet'])->name('addDishInSet');

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row page-titles m-0 mx-0 mt-md-4">
        <div class="col-sm-6 p-0 p-md-2">
            <div class="welcome-text">
                <h4>Корзина</h4>
                <p class="mb-0">Your business dashboard template</p>
            </div>
        </div>
    </div>
    <div class="row cart card p-2 p-sm-3 p-md-5">
        <div class="col" id="cart">
            <div class="cart__item-box">
                <!-- <div class="cart__item">
                    <div class="cart__item-name"></div>
                    <div class="cart__item-count"></div>
                    <div class="cart__item-price"></div>
                </div> -->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Название</th>
                            <th scope="col">Количество</th>
                            <th scope="col">Цена</th>
                        </tr>
                    </thead>
                    <tbody class="cart-table-body">
                    </tbody>
                    <tbody>
                        <tr>
                            <td>Итого: <span class="cart-summ">0</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-12 text-right">
            <button class="btn btn-primary send-order" data-toggle="modal" data-target="#order">Сделать заказ</button>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="order">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Оформление заказа</h5>
            </div>
            <div class="modal-body">
                    <div class="mb-3">
                        <label for="phone" class="form-label">Телефон</label>
                        <input type="text" class="form-control" id="phone" name="phone" aria-describedby="phone">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Адрес</label>
                        <input type="text" class="form-control" id="address" name="address">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="comment">Комментарий</label>
                        <input type="text" class="form-control" id="comment" name="comment">
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="send-order">Заказать</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="thanks">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Заказ оформлен</h5>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    Спасибо за заказ!
                </div>
            </div>
            <div class="modal-footer">
                <a href="/" class="btn btn-secondary">На главную</a>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')
<script>
    updateCart();

    /**
     * {
     * 
     *  rst_id: 15, 
     *  dishes: [
     *      { 
     *          id:    12
     *          name:  'Ролы Филадельфия'
     *          price: 124
     *          count: 1  
     *      },
     *      { 
     *          id:    17
     *          name:  'Картошка Фри'
     *          price: 250
     *          count: 3
     *      },
     *  ]
     * 
     * }
     */
    function getCart() {
        let cart = localStorage.getItem('cart');
        let defaultCart = {
            rst_id: null,
            dishes: []
        }
        if (cart != null) {
            return JSON.parse(cart);
        } else {
            localStorage.setItem('cart', JSON.stringify(defaultCart));
            return defaultCart;
        }
    }

    function clearCart() {
        localStorage.removeItem('cart');
    }

    function findDishIdInCart(dishesArr, searchId) {
        let cartDishId = dishesArr.findIndex(dish => dish.id === searchId)
        return cartDishId;
    }

    function updateCart() {
        let cart = getCart();
        let cartHTML = $('#cart').find('.cart-table-body');
        let spanCount = $('.count-cart');
        let cartSummHtml = $('.cart-summ');
        let html = '';
        let allCount = 0;
        let summ = 0;

        for (const [index, dish] of cart.dishes.entries()) {
            html += '<tr>\
                        <td>' + (index + 1) + '</td>\
                        <td>' + dish.name + '</td>\
                        <td>' + dish.count + '</td>\
                        <td>' + dish.price * dish.count + '</td>\
                    </tr>';
            let proPrice = dish.price * dish.count;
            allCount += dish.count;
            summ += proPrice;
        }

        cartHTML.html(html);
        spanCount.html(allCount);
        cartSummHtml.html(summ);
    }


    $('.to-cart').on('click', function() {
        let cart = getCart();
        let dishId = $(this).closest('.card').find('[name="dishId"]');
        let rst = $(this).closest('.card').find('[name="rstId"]');

        $.post('/admin/dish/getDishById', {
            '_token': $('meta[name="csrf-token"]').attr('content'),
            dishId: dishId.val()
        }, function(res) {
            cart.rst_id = rst.val();

            // проверяем есть ли в корзине такой товар с таким идентификатором
            let cartDishId = findDishIdInCart(cart.dishes, res.id);

            // если товар найден в корзине, то прибавляем количество
            // иначе добавляем новый товар
            if (cartDishId == -1) {
                cart.dishes.push({
                    id: res.id,
                    name: res.name,
                    price: res.price,
                    count: 1
                })
            } else {
                cart.dishes[cartDishId].count++;
            }

            localStorage.setItem('cart', JSON.stringify(cart));
            updateCart();
        });
    })

    $('#send-order').on('click', function() {
        let cart = getCart();
        let address = $('[name="address"]').val();
        let phone = $('[name="phone"]').val();
        let comment = $('[name="comment"]').val();
        let modalOrder = $('#order');
        let modalThanks = $('#thanks');
        let spanCount = $('.count-cart');
        let cartHTML = $('#cart');

        $.post('/admin/orders/store', {
            '_token': $('meta[name="csrf-token"]').attr('content'),
            cart: cart,
            address: address,
            phone: phone,
            comment: comment,
        }, function(res) {
            modalOrder.modal('hide');
            modalThanks.modal('show');
            clearCart();
            spanCount.html('0');
            cartHTML.html(' <table class="table">\
                    <thead>\
                        <tr>\
                            <th scope="col">#</th>\
                            <th scope="col">Название</th>\
                            <th scope="col">Количество</th>\
                            <th scope="col">Цена</th>\
                        </tr>\
                    </thead>\
                    <tbody class="cart-table-body">\
                    </tbody>\
                    <tbody>\
                        <tr>\
                            <td>Итого: <span class="cart-summ">0</span></td>\
                        </tr>\
                    </tbody>\
                </table>');
            console.log(res);
        })
    })
</script>
@endsection

resources/views/companies.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-between">
        @foreach($companies as $company)
        <div class="col-3 company">
            <a href="{{ route('company', ['id' => $company->id]) }}">
                <div class="row">
                    <div class="col-12 p-0">
                        <div class="img">
                            <img src="{{ asset('img/bk.webp') }}" alt="">
                        </div>
                    </div>
                    <div class="col-12 py-2">
                        <h4>{{ $company->name }}</h4>
                        <p>г. {{ $company->city->name }}</p>
                    </div>
                </div>
            </a>
        </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/company.blade.php
@extends('layouts.shop')

@section('styles')
@livewireStyles
@endsection

@section('content')
<div class="container-fluid">
    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="welcome-text">
                <h4>{{ $company->name }}</h4>
                <p class="mb-0">Your business dashboard template</p>
            </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Layout</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Blank</a></li>
            </ol>
        </div>
    </div>
    <div class="row">
    @foreach($company->dishes as $dish)
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="{{ asset('img/basket.jpg') }}" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>{{ $dish->name }}</h4>
                            <p>{{ $dish->weight }} {{ $dish->unit->name}}</p>
                            <!-- <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                            </ul> -->
                            <span class="price">{{ $dish->price }}р.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/2.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>Striped Dress</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                            <span class="price">$159.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/3.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>BBow polka-dot</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                            <span class="price">$357.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/4.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>Z Product 360</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                            </ul>
                            <span class="price">$654.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/5.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>Chair Grey</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                            <span class="price">$369.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/6.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>fox sake withe</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                            <span class="price">$245.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/7.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>Back Bag</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                            <span class="price">$364.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="new-arrival-product">
                        <div class="new-arrivals-img-contnent">
                            <img class="img-fluid" src="images/product/1.jpg" alt="">
                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>FLARE DRESS</h4>
                            <ul class="star-rating">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                                <li><i class="fa fa-star-half-empty"></i></li>
                            </ul>
                            <span class="price">$548.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
<div class="row">
    <div class="col">
    <livewire:cart />
    </div>
</div>
</div>
@endsection

@section('scripts')
@livewireScripts
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
                <order :orders="{{ $orders }}" :company="{{ $company }}"/>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('css')
@livewireStyles

<link rel="stylesheet" href="{{ asset('libs/owlcarousel/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('libs/owlcarousel/css/owl.theme.default.min.css') }}">
<style>
    .sale-img-container {
        margin-right: 20px;
        box-shadow: 0 7px 20px -8px rgb(157 157 163 / 50%);
        border-radius: 16px;
        width: 262px;
        overflow: hidden;
        height: 162px;
        transition: all 0.2s ease;
    }

    .sale-img-container:hover {
        box-shadow: 0 7px 19px -1px rgb(172 172 179 / 50%);
        transform: translateY(-6px);
    }
</style>
@endsection

@section('content')

<div class="container mt-5">
    <div class="row owl-carousel">
        @for ($i = 1; $i <= 5; $i++) 
        <div class="col sale-img-container p-0">
            <div class="">
                <img src="{{ asset('img/sale/' . $i . '.jpeg') }}" alt="">
            </div>
        </div>
        @endfor
</div>
<div class="row">
    <div class="col">
        <h1>Рестораны</h1>
    </div>
</div>
<div class="row">
    @foreach($companies as $company)
    <div class="col-xl-4 col-lg-6 col-md-4 col-sm-6">
        <div class="card restaurant">
            <div class="card-body p-0">
                <a href="{{ route('rst.index', ['id' => $company->id]) }}">
                    <div class="new-arrival-product">
                        <div class="rst-con">

                        </div>
                        <div class="new-arrival-content text-center mt-3">
                            <h4>{{ $company->name }}</h4>
                            <p>г. {{ $company->city->name }}</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    @endforeach
</div>
</div>
@endsection

@section('js')
@livewireScripts

<script src="{{ asset('libs/owlcarousel/js/owl.carousel.min.js') }}"></script>

<script>
    $('.owl-carousel').owlCarousel({
        loop: true,
        margin: 10,
        nav: false,
        responsive: {
            0: {
                items: 1
            },
            600: {
                items: 3
            },
            1000: {
                items: 4
            }
        }
    })
</script>
@endsection