routes/web.php
<?php

use App\Http\Controllers\Admin\Categories\CategoriesController;
use App\Http\Controllers\Admin\Orders\OrdersController;
use App\Http\Controllers\Admin\Settings\SettingsController;
use App\Http\Controllers\Admin\Dishes\DishesController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Restaurant\RestaurantController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Тестовые роуты
 */
Route::get('city', [IndexController::class, 'city']);
/** */

Route::get('/', [IndexController::class, 'index'])->name('index');
//
Route::get('/eve', [HomeController::class, 'eve'])->name('eve');

Route::post('messages', [RestaurantController::class,'comment'])->name('messages');

Route::get('/company/{id}', [IndexController::class, 'company'])->name('company');
Route::get('/companies', [IndexController::class, 'companies'])->name('companies');
Route::get('/shop', function () {
    return view('shop');
})->name('shop');

// Корзина
Route::get('/cart', [CartController::class, 'index'])->name('cart');

// Ресторан
Route::as('rst.')
    ->prefix('/rst')
   // ->namespace('Restaurant')
    ->group(function () {
        Route::get('{id}', [RestaurantController::class,'index'])->name('index');
    });

// Админка
Route::as('admin.')
    ->prefix('/admin')
    //->namespace('Admin')
    ->middleware('auth')
    ->group(function () {

        Route::get('/', [AdminIndexController::class, 'index'])->name('index');

        // Раздел управления категориями
        
        Route::as('categories.')
            ->prefix('/categories')
           // ->namespace('Categories')
            ->group(function () {
                Route::get('/', [CategoriesController::class, 'index'])->name('index');
                Route::post('/', [CategoriesController::class, 'store'])->name('store');
                Route::put('/{id}', [CategoriesController::class, 'update'])->name('update');
                Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
                Route::get('/create', [CategoriesController::class, 'create'])->name('create');
                Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
            }
        );

        // Раздел управления блюдами
        Route::as('dish.')
            ->prefix('/dish')
          //  ->namespace('Dish')
            ->group(function () {
                Route::get('/', [DishesController::class, 'index'])->name('index');
                Route::get('add', [DishesController::class, 'add'])->name('add');
                Route::get('edit/{id}', [DishesController::class, 'edit'])->name('edit');
                Route::post('store', [DishesController::class, 'store'])->name('store');
                Route::post('update', [DishesController::class, 'update'])->name('update');
                Route::post('delete', [DishesController::class, 'delete'])->name('delete');

                Route::post('getDishById', [DishesController::class, 'getDishById'])->name('getDishById');
            });

        // Раздел управления заказами
        Route::as('orders.')
            ->prefix('/orders')
         //   ->namespace('Orders')
            ->group(function () {
                Route::get('/', [OrdersController::class, 'index'])->name('index');
                Route::post('/store', [OrdersController::class, 'store'])->name('store');
                Route::get('/order/{orderId}', [OrdersController::class, 'order'])->name('order');
            });

        // Раздел настройки
        Route::as('settings.')
            ->prefix('/settings')
          //  ->namespace('Settings')
            ->group(function () {
                Route::get('/', [SettingsController::class, 'index'])->name('index');
            });
    });

Route::post('/addDishInSet', [IndexController::class, 'addDishInSet'])->name('addDishInSet');

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Dish.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'category_id',
        'unit_id',
        'description',
        'weight',
        'price',
        'image',
        'company_id'
    ];

    public function unit()
    {
        return $this->belongsTo(Unit::class);
    }

    public function cart()
    {
        return $this->hasMany(CartTelegramChat::class);
    }
}

app/Http/Controllers/API/v1/Dishes/DishesController.php
<?php

namespace App\Http\Controllers\API\v1\Dishes;

use App\Http\Controllers\Controller;
use App\Http\Resources\Dishes\DishCollection;
use App\Http\Resources\Dishes\DishResource;
use App\Models\Dish;
use Illuminate\Http\Request;
use App\Services\Dish\DishService;
use Illuminate\Support\Facades\Auth;

class DishesController extends Controller
{
    /**
     * @var DishService
     */
    protected $dishService;

    public function __construct(
        DishService $dishService
    ) {
        $this->dishService = $dishService;
    }

    public function index()
    {
        $dishes = $this->dishService->getCompanyDishes(1);
        return new DishCollection($dishes);
    }

    public function getByCategory(Request $request)
    {
        $perPage = (int) $request->per_page ?: 15;
        $dishes = $this->dishService->getByCategory($request->ci, $perPage);
        return new DishCollection($dishes);
    }

    public function getById(Request $request)
    {
        $dish = Dish::where('id', $request->di)->with('cart', function($q) use ($request) {
            $q->where('telegram_chat_id', $request->tci)
            ->where('dish_id', $request->di);
        })->find($request->di);
        return new DishResource($dish);
    }

    public function store(Request $request)
    {
       
    }

    public function update(Request $request)
    {
       
    }

    public function delete(Request $request)
    {
        
    }
}

app/Http/Controllers/Admin/Dishes/DishesController.php
<?php

namespace App\Http\Controllers\Admin\Dishes;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Unit;
use App\Models\Category;
use App\Models\Dish;
use App\Services\Dish\DishService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class DishesController extends Controller
{
    /**
     * @var DishService
     */
    protected $dishService;

    public function __construct(
        DishService $dishService
    ) {
        $this->dishService = $dishService;
    }

    public function index()
    {
        $dishes = $this->dishService->getCompanyDishes(Auth::user()->company_id);
        return view('admin.dish.index', compact('dishes'));
    }

    /**
     * Возвращает блюдо по идентификатору
     * 
     * @param Request
     * 
     * @return
     */
    public function getDishById(Request $request)
    {
        return $this->dishService->getDishById($request->dishId);
    }

    public function add()
    {
        $categories = Category::get();
        $units      = Unit::get();

        return view('admin.dish.add', compact('categories', 'units'));
    }

    public function edit($id)
    {
        $categories = Category::get();
        $units      = Unit::get();
        $dish       = Dish::find($id);

        return view('admin.dish.edit', compact('categories', 'units', 'dish'));
    }

    public function store(Request $request)
    {
        $dish = $this->dishService->storeDish($request->toArray());
        return redirect(route('admin.dish.index'));
    }

    public function update(Request $request)
    {
        $updateDish = $this->dishService->updateDish($request->id, $request->toArray());
        return redirect(route('admin.dish.index'));
    }

    public function delete(Request $request)
    {
        $deleteDish = $this->dishService->deleteDish($request->dishId);
        return redirect(route('admin.dish.index'));
    }
}

resources/views/admin/dish/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="welcome-text">
                <h4>Меню</h4>
            </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Админпанель</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Меню</a></li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="ml-auto">
                        <a href="{{ route('admin.dish.add') }}">Добавить блюдо</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-responsive-md">
                            <thead>
                                <tr>
                                    <!-- <th style="width:50px;">
                                        <div class="custom-control custom-checkbox checkbox-success check-lg mr-3">
                                            <input type="checkbox" class="custom-control-input" id="checkAll" required="">
                                            <label class="custom-control-label" for="checkAll"></label>
                                        </div>
                                    </th> -->
                                    <th><strong>№</strong></th>
                                    <th><strong>Наименование</strong></th>
                                    <th><strong>Вес</strong></th>
                                    <th><strong>Цена</strong></th>
                                    <th><strong>Status</strong></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($dishes as $dish)
                                <tr>
                                    <!-- <td>
                                        <div class="custom-control custom-checkbox checkbox-success check-lg mr-3">
                                            <input type="checkbox" class="custom-control-input" id="customCheckBox2" required="">
                                            <label class="custom-control-label" for="customCheckBox2"></label>
                                        </div>
                                    </td> -->
                                    <td><strong>{{ $dish->id }}</strong></td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <img src="{{ Storage::disk('public')->url($dish->image) }}" class="rounded-lg mr-2" width="24" alt="" />
                                            <a href="{{ route('admin.dish.edit',['id' => $dish->id ]) }}">
                                                <span class="w-space-no">{{ $dish->name }}</span>
                                            </a>
                                        </div>
                                    </td>
                                    <td>{{ $dish->weight }} {{ $dish->unit->name }}</td>
                                    <td>{{ $dish->price }}</td>
                                    <td>
                                        <div class="d-flex align-items-center"><i class="fa fa-circle text-success mr-1"></i> Successful</div>
                                    </td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="{{ route('admin.dish.edit', ['id' => $dish->id]) }}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-pencil"></i></a>
                                            <a href="#" class="btn btn-danger shadow btn-xs sharp delete-dish" data-dish-id="{{ $dish->id }}"><i class="fa fa-trash"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-delete-dish">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('admin.dish.delete') }}" method="POST" id="form-delete-dish">
                @csrf
                <input type="hidden" name="dishId">
                <div class="modal-header">
                    <h5 class="modal-title">Удаление блюда</h5>
                    <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">Вы действительно хотите удалить это блюдо?</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary light" data-dismiss="modal">Нет</button>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script>
    $('.delete-dish').on('click', function(e) {
        e.preventDefault();
        let modal = $('#modal-delete-dish');
        let dishId = $(this).data('dish-id');
        let form = $('#form-delete-dish');

        form.find("[name='dishId']").val(dishId);

        modal.modal('show');
    });
</script>

@endsection