routes/web.php
<?php

use App\Http\Controllers\Admin\Categories\CategoriesController;
use App\Http\Controllers\Admin\Orders\OrdersController;
use App\Http\Controllers\Admin\Settings\SettingsController;
use App\Http\Controllers\Admin\Dishes\DishesController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Restaurant\RestaurantController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Тестовые роуты
 */
Route::get('city', [IndexController::class, 'city']);
/** */

Route::get('/', [IndexController::class, 'index'])->name('index');
//
Route::get('/eve', [HomeController::class, 'eve'])->name('eve');

Route::post('messages', [RestaurantController::class,'comment'])->name('messages');

Route::get('/company/{id}', [IndexController::class, 'company'])->name('company');
Route::get('/companies', [IndexController::class, 'companies'])->name('companies');
Route::get('/shop', function () {
    return view('shop');
})->name('shop');

// Корзина
Route::get('/cart', [CartController::class, 'index'])->name('cart');

// Ресторан
Route::as('rst.')
    ->prefix('/rst')
   // ->namespace('Restaurant')
    ->group(function () {
        Route::get('{id}', [RestaurantController::class,'index'])->name('index');
    });

// Админка
Route::as('admin.')
    ->prefix('/admin')
    //->namespace('Admin')
    ->middleware('auth')
    ->group(function () {

        Route::get('/', [AdminIndexController::class, 'index'])->name('index');

        // Раздел управления категориями
        
        Route::as('categories.')
            ->prefix('/categories')
           // ->namespace('Categories')
            ->group(function () {
                Route::get('/', [CategoriesController::class, 'index'])->name('index');
                Route::post('/', [CategoriesController::class, 'store'])->name('store');
                Route::put('/{id}', [CategoriesController::class, 'update'])->name('update');
                Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
                Route::get('/create', [CategoriesController::class, 'create'])->name('create');
                Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
            }
        );

        // Раздел управления блюдами
        Route::as('dish.')
            ->prefix('/dish')
          //  ->namespace('Dish')
            ->group(function () {
                Route::get('/', [DishesController::class, 'index'])->name('index');
                Route::get('add', [DishesController::class, 'add'])->name('add');
                Route::get('edit/{id}', [DishesController::class, 'edit'])->name('edit');
                Route::post('store', [DishesController::class, 'store'])->name('store');
                Route::post('update', [DishesController::class, 'update'])->name('update');
                Route::post('delete', [DishesController::class, 'delete'])->name('delete');

                Route::post('getDishById', [DishesController::class, 'getDishById'])->name('getDishById');
            });

        // Раздел управления заказами
        Route::as('orders.')
            ->prefix('/orders')
         //   ->namespace('Orders')
            ->group(function () {
                Route::get('/', [OrdersController::class, 'index'])->name('index');
                Route::post('/store', [OrdersController::class, 'store'])->name('store');
                Route::get('/order/{orderId}', [OrdersController::class, 'order'])->name('order');
            });

        // Раздел настройки
        Route::as('settings.')
            ->prefix('/settings')
          //  ->namespace('Settings')
            ->group(function () {
                Route::get('/', [SettingsController::class, 'index'])->name('index');
            });
    });

Route::post('/addDishInSet', [IndexController::class, 'addDishInSet'])->name('addDishInSet');

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="_token" content="{{ csrf_token() }}" />
    <title>Davur - Restaurant Food Order Bootstrap Admin Dashboard</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.png">
    <link href="{{ asset('vendor/jqvmap/css/jqvmap.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('vendor/chartist/css/chartist.min.css')}}">
    <link href="{{ asset('vendor/bootstrap-select/dist/css/bootstrap-select.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    <link href="{{ asset('css/style.css')}}" rel="stylesheet">
    <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">
    <link href="{{ asset('css/custom-style.css')}}" rel="stylesheet">
    

    @yield('styles')

</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    <div id="main-wrapper">

        @include('admin.layouts.nav-header')
        
        @include('admin.layouts.header')
        @include('admin.layouts.nav')

        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body" id="app">
            @yield('content')
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

        @include('admin.layouts.footer')

    </div>
    <!--**********************************
        Scripts
    ***********************************-->

    <script src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
			}
		});
	</script>
    <!-- Required vendors -->
    <script src="{{ asset('vendor/global/global.min.js')}}"></script>
    <script src="{{ asset('vendor/bootstrap-select/dist/js/bootstrap-select.min.js')}}"></script>
    <script src="{{ asset('vendor/chart.js/Chart.bundle.min.js')}}"></script>
    <script src="{{ asset('js/custom.min.js')}}"></script>
    <script src="{{ asset('js/deznav-init.js')}}"></script>

    <!-- Counter Up -->
    <script src="{{ asset('vendor/waypoints/jquery.waypoints.min.js')}}"></script>
    <script src="{{ asset('vendor/jquery.counterup/jquery.counterup.min.js')}}"></script>
    
    @yield('scripts')

</body>

</html>

resources/views/admin/layouts/footer.blade.php
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by <a href="http://dexignzone.com/" target="_blank">DexignZone</a> 2020</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

resources/views/admin/layouts/header.blade.php
		<!--**********************************
            Header start
        ***********************************-->
		<div class="header">
		    <div class="header-content">
		        <nav class="navbar navbar-expand">
		            <div class="collapse navbar-collapse justify-content-between">
		                <div class="header-left">
		                    <!-- <div class="search_bar dropdown show">
		                        <div class="dropdown-menu p-0 m-0 show">
		                            <form>
		                                <input class="form-control" type="search" placeholder="Search Here" aria-label="Search">
		                            </form>
		                        </div>
		                        <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
		                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
		                                <path d="M23.7871 22.7761L17.9548 16.9437C19.5193 15.145 20.4665 12.7982 20.4665 10.2333C20.4665 4.58714 15.8741 0 10.2333 0C4.58714 0 0 4.59246 0 10.2333C0 15.8741 4.59246 20.4665 10.2333 20.4665C12.7982 20.4665 15.145 19.5193 16.9437 17.9548L22.7761 23.7871C22.9144 23.9255 23.1007 24 23.2816 24C23.4625 24 23.6488 23.9308 23.7871 23.7871C24.0639 23.5104 24.0639 23.0528 23.7871 22.7761ZM1.43149 10.2333C1.43149 5.38004 5.38004 1.43681 10.2279 1.43681C15.0812 1.43681 19.0244 5.38537 19.0244 10.2333C19.0244 15.0812 15.0812 19.035 10.2279 19.035C5.38004 19.035 1.43149 15.0865 1.43149 10.2333Z" fill="#A4A4A4" /></svg>
		                        </span>
		                    </div> -->
		                </div>

		                <ul class="navbar-nav header-right">
		                   
		                    <li class="nav-item dropdown header-profile">
		                        <a class="nav-link" href="#" role="button" data-toggle="dropdown">
		                            <div class="header-info">
		                                <span>Привет, <strong>{{ Auth::user()->name }}</strong></span>
		                            </div>
		                            <img src="/images/profile/pic1.jpg" width="20" alt="" />
		                        </a>
		                        <div class="dropdown-menu dropdown-menu-right">
		                            <a href="./app-profile.html" class="dropdown-item ai-icon">
		                                <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
		                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
		                                    <circle cx="12" cy="7" r="4"></circle>
		                                </svg>
		                                <span class="ml-2">Profile </span>
		                            </a>
		                            <a href="./email-inbox.html" class="dropdown-item ai-icon">
		                                <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
		                                    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
		                                    <polyline points="22,6 12,13 2,6"></polyline>
		                                </svg>
		                                <span class="ml-2">Inbox </span>
		                            </a>
		                            <a href="./page-login.html" class="dropdown-item ai-icon">
		                                <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
		                                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
		                                    <polyline points="16 17 21 12 16 7"></polyline>
		                                    <line x1="21" y1="12" x2="9" y2="12"></line>
		                                </svg>
		                                <span class="ml-2">Logout </span>
		                            </a>
		                        </div>
		                    </li>
		                </ul>
		            </div>
		        </nav>
		    </div>
		</div>
		<!--**********************************
            Header end ti-comment-alt
        ***********************************-->

resources/views/admin/layouts/nav-header.blade.php
        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="/" class="brand-logo">
                <img class="logo-abbr" src="/images/logo.png" alt="">
               <span style="font-size: 32px; font-weight: 700; font-family: Roboto; color: #000; margin-left: 10px"> DISHBOT</span>
                <!-- <img class="logo-compact" src="/images/logo-text.png" alt="">
                <img class="brand-title" src="/images/logo-text.png" alt=""> -->
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

resources/views/admin/layouts/nav.blade.php
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="deznav">
            <div class="deznav-scroll">
                <div class="add-menu-sidebar">
                    <img src="/images/icon1.png" alt="" />
                    <p>Организуйте свое меню с помощью кнопки ниже</p>
                    <a href="{{ route('admin.dish.add') }}" class="btn btn-primary btn-block light">+ Добавить блюдо</a>
                </div>
                <ul class="metismenu" id="menu">
                    <li><a class="has-arrow ai-icon" href="{{ route('admin.index') }}" aria-expanded="false">
                            <i class="flaticon-381-television"></i>
                            <span class="nav-text">Рабочий стол</span>
                        </a>
                    </li>
                    <li><a class="has-arrow ai-icon" href="{{ route('admin.categories.index') }}" aria-expanded="false">
                            <i class="flaticon-381-app"></i>
                            <span class="nav-text">Категории</span>
                        </a>
                    </li>
                    <li><a class="has-arrow ai-icon" href="{{ route('admin.dish.index') }}" aria-expanded="false">
                            <i class="flaticon-381-notepad-2"></i>
                            <span class="nav-text">Меню</span>
                        </a>
                    </li>
                    <li><a class="has-arrow ai-icon" href="{{ route('admin.orders.index') }}" aria-expanded="false">
                            <i class="flaticon-381-ring"></i>
                            <span class="nav-text">Заказы</span>
                        </a>
                    </li>
                    <li><a class="has-arrow ai-icon" href="{{ route('admin.settings.index') }}" aria-expanded="false">
                            <i class="flaticon-381-settings-6"></i>
                            <span class="nav-text">Настройки</span>
                        </a>
                    </li>
                    <li><a class="has-arrow ai-icon" href="{{ route('logout') }}" aria-expanded="false" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
                            <i class="flaticon-381-exit-2"></i>
                            <span class="nav-text">Выход</span>
                        </a>
                        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>

            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->