routes/web.php
<?php

use App\Http\Controllers\Admin\Categories\CategoriesController;
use App\Http\Controllers\Admin\Orders\OrdersController;
use App\Http\Controllers\Admin\Settings\SettingsController;
use App\Http\Controllers\Admin\Dishes\DishesController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Restaurant\RestaurantController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Тестовые роуты
 */
Route::get('city', [IndexController::class, 'city']);
/** */

Route::get('/', [IndexController::class, 'index'])->name('index');
//
Route::get('/eve', [HomeController::class, 'eve'])->name('eve');

Route::post('messages', [RestaurantController::class,'comment'])->name('messages');

Route::get('/company/{id}', [IndexController::class, 'company'])->name('company');
Route::get('/companies', [IndexController::class, 'companies'])->name('companies');
Route::get('/shop', function () {
    return view('shop');
})->name('shop');

// Корзина
Route::get('/cart', [CartController::class, 'index'])->name('cart');

// Ресторан
Route::as('rst.')
    ->prefix('/rst')
   // ->namespace('Restaurant')
    ->group(function () {
        Route::get('{id}', [RestaurantController::class,'index'])->name('index');
    });

// Админка
Route::as('admin.')
    ->prefix('/admin')
    //->namespace('Admin')
    ->middleware('auth')
    ->group(function () {

        Route::get('/', [AdminIndexController::class, 'index'])->name('index');

        // Раздел управления категориями
        
        Route::as('categories.')
            ->prefix('/categories')
           // ->namespace('Categories')
            ->group(function () {
                Route::get('/', [CategoriesController::class, 'index'])->name('index');
                Route::post('/', [CategoriesController::class, 'store'])->name('store');
                Route::put('/{id}', [CategoriesController::class, 'update'])->name('update');
                Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
                Route::get('/create', [CategoriesController::class, 'create'])->name('create');
                Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
            }
        );

        // Раздел управления блюдами
        Route::as('dish.')
            ->prefix('/dish')
          //  ->namespace('Dish')
            ->group(function () {
                Route::get('/', [DishesController::class, 'index'])->name('index');
                Route::get('add', [DishesController::class, 'add'])->name('add');
                Route::get('edit/{id}', [DishesController::class, 'edit'])->name('edit');
                Route::post('store', [DishesController::class, 'store'])->name('store');
                Route::post('update', [DishesController::class, 'update'])->name('update');
                Route::post('delete', [DishesController::class, 'delete'])->name('delete');

                Route::post('getDishById', [DishesController::class, 'getDishById'])->name('getDishById');
            });

        // Раздел управления заказами
        Route::as('orders.')
            ->prefix('/orders')
         //   ->namespace('Orders')
            ->group(function () {
                Route::get('/', [OrdersController::class, 'index'])->name('index');
                Route::post('/store', [OrdersController::class, 'store'])->name('store');
                Route::get('/order/{orderId}', [OrdersController::class, 'order'])->name('order');
            });

        // Раздел настройки
        Route::as('settings.')
            ->prefix('/settings')
          //  ->namespace('Settings')
            ->group(function () {
                Route::get('/', [SettingsController::class, 'index'])->name('index');
            });
    });

Route::post('/addDishInSet', [IndexController::class, 'addDishInSet'])->name('addDishInSet');

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'company_id'
    ];

    public function dishes()
    {
        return $this->hasMany(Dish::class);
    }
}

app/Http/Controllers/API/v1/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\API\v1\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CategoryListRequest;
use App\Http\Resources\Categories\CategoryCollection;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * @var CategoryService
     */
    protected $categoryService;

    public function __construct(
        CategoryService $categoryService
    ) {
        $this->categoryService = $categoryService;
    }

    public function index(Request $request)
    {
        $validated = [
            'company_id' => $request->company_id,
            'per_page'   => $request->per_page ? $request->per_page : 15
        ];

        $categories = $this->categoryService->paginate($validated);
        return new CategoryCollection($categories);
    }

    public function store()
    {

    }

    public function update()
    {

    }

    public function delete()
    {
        
    }
}

app/Http/Controllers/Admin/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * @var CategoryService
     */
    protected $categoryService;

    public function __construct(
        CategoryService $categoryService
    ) {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $categories = $this->categoryService->getAll();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.add');
    }

    public function edit($id)
    {
        $category = Category::find($id);
        return view('admin.categories.edit', compact('category'));
    }

    public function store(Request $request)
    {
        Category::create([
            'name' => $request->name,
            'company_id' => auth()->user()->company_id
        ]);

        return redirect(route('admin.categories.index'));
    }

    public function update($id, Request $request)
    {
        $category = Category::where('id', $id)->update([
            'name' => $request->name
        ]);

        return redirect(route('admin.categories.index'));
    }

    public function destroy($id)
    {
        $category = Category::find($id);

        $category->delete();

        return redirect(route('admin.categories.index'));
    }
}

resources/views/admin/categories/add.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Главная</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Добавление категории</a></li>
                </ol>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Данные категории</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form method="post" id="dish-form" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group col">
                                <label>Название категории</label>
                                <input type="text" class="form-control" name="name" value="" required>
                            </div>
                            <div class="form-group col">
                                <button type="submit" id="addDish" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

    @section('scripts')

    @endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Главная</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Добавление категории</a></li>
                </ol>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Редактировать категорию</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form method="POST" action="{{ route('admin.categories.update', $category->id) }}" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="form-group col">
                                <label>Название категории</label>
                                <input type="text" class="form-control" name="name" value="{{ $category->name }}" required>
                            </div>
                            <div class="form-group col">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

    @section('scripts')

    @endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="welcome-text">
                <h4>Категории</h4>
            </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Админпанель</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Категории</a></li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Таблица категорий</h4>
                    <div class="text-right">
                        <a href="{{ route('admin.categories.create') }}">Добавить категорию</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-responsive-md">
                            <thead>
                                <tr>
                                    <!-- <th style="width:50px;">
                                        <div class="custom-control custom-checkbox checkbox-success check-lg mr-3">
                                            <input type="checkbox" class="custom-control-input" id="checkAll" required="">
                                            <label class="custom-control-label" for="checkAll"></label>
                                        </div>
                                    </th> -->
                                    <th><strong>№</strong></th>
                                    <th><strong>Наименование</strong></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($categories as $category)
                                <tr>
                                    <!-- <td>
                                        <div class="custom-control custom-checkbox checkbox-success check-lg mr-3">
                                            <input type="checkbox" class="custom-control-input" id="customCheckBox2" required="">
                                            <label class="custom-control-label" for="customCheckBox2"></label>
                                        </div>
                                    </td> -->
                                    <td><strong>{{ $category->id }}</strong></td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <a href="{{ route('admin.categories.edit', $category->id) }}">
                                                <span class="w-space-no">{{ $category->name }}</span>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-pencil"></i></a>
                                            <a href="#" class="btn btn-danger shadow btn-xs sharp delete-category" data-category-id="{{ $category->id }}"><i class="fa fa-trash"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-delete-category">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('admin.categories.destroy', $category->id) }}" method="POST" id="form-delete-category">
                @csrf
                @method('DELETE')
                <input type="hidden" name="categoryId">
                <div class="modal-header">
                    <h5 class="modal-title">Удаление категории</h5>
                    <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">Вы действительно хотите удалить эту категорию?</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary light" data-dismiss="modal">Нет</button>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script>
    $('.delete-category').on('click', function(e) {
        e.preventDefault();
        let modal = $('#modal-delete-category');
        let categoryId = $(this).data('category-id');
        let form = $('#form-delete-category');
        let url = '{{ route("admin.categories.destroy", ":id") }}'
        url = url.replace(':id', categoryId);

        form.find("[name='categoryId']").val(categoryId);
        form.attr('action', url)

        modal.modal('show');
    });
</script>

@endsection